all:
	cd src && nmake all
	cd process && nmake all

winkey:
	cd src && nmake all

process:
	cd process && nmake all

clean:
	cd src && nmake clean
	cd process && nmake clean

fclean:
	cd src && nmake fclean
	cd process && nmake fclean

re:
	cd src && nmake re
	cd process && nmake re
